# Generated by Django 5.0 on 2024-03-27 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.BooleanField(default=False)),
                ('asian', models.BooleanField(default=False)),
                ('black', models.BooleanField(default=False)),
                ('hispanic', models.BooleanField(default=False)),
                ('pacific', models.BooleanField(default=False)),
                ('white', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('unanswered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Non-Binary/Other')], max_length=1)),
                ('occupation', models.CharField(choices=[('ss', 'K-12 Student'), ('st', 'K-12 Teacher'), ('us', 'Undergraduate Student'), ('gs', 'Graduate Student'), ('pd', 'Postdoctorate'), ('cf', 'University/College Faculty'), ('cs', 'University/College Staff'), ('iu', 'Industrial User'), ('gu', 'Government User'), ('uu', 'Unaffiliated User'), ('nu', 'Nonprofit User'), ('oo', 'Other'), ('np', 'Not Provided')], max_length=2)),
                ('source', models.CharField(choices=[('fr', 'Friend'), ('sd', 'Student'), ('is', 'Instructor'), ('cl', 'Colleague'), ('ws', 'Workshop'), ('cv', 'Convention'), ('de', 'Direct Email'), ('se', 'Search Engine'), ('in', 'Internet'), ('gb', 'UCSC Genome Browser'), ('sm', 'Social Media'), ('oo', 'Other'), ('np', 'Not Provided')], max_length=2)),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ethnicity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
