# Generated by Django 3.2.25 on 2024-04-11 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=160)),
                ('sequencing_type', models.CharField(choices=[('nanopore', 'Nanopore'), ('sanger', 'Sanger'), ('illumina', 'Illumina'), ('', 'Unknown')], default='sanger', max_length=8)),
                ('project_type', models.CharField(choices=[('PHY', 'Phylogenetics'), ('NGS', 'Next Generation Sequencing'), ('UB', 'uBiome')], default='phylogenetics', max_length=3)),
                ('public', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', True), _negated=True), fields=('user', 'title'), name='unique_non_deleted_title_per_user'),
        ),
    ]
