# Generated by Django 3.2.25 on 2024-04-19 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20240411_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reads', models.TextField()),
                ('trace_exists', models.BooleanField(default=False)),
                ('is_consensus', models.BooleanField(default=False)),
                ('trim_start', models.IntegerField(blank=True, null=True)),
                ('trim_end', models.IntegerField(blank=True, null=True)),
                ('read_type', models.CharField(choices=[('F', 'Forward'), ('R', 'Reverse'), ('C', 'Consensus')], max_length=1)),
                ('associated_abi', models.FileField(blank=True, null=True, upload_to='abi_files/')),
                ('associated_fasta', models.FileField(upload_to='fasta_files/')),
                ('is_public', models.BooleanField(default=False)),
                ('forward_read', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consensus_forward', to='backend.datafile')),
                ('reverse_read', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consensus_reverse', to='backend.datafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
