# Generated by Django 3.2.25 on 2024-04-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_datafile_projectdatafile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdatafile',
            unique_together={('project', 'data_file')},
        ),
    ]
