# Generated by Django 3.2.25 on 2024-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_projectdatafile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='associated_fasta',
            field=models.FileField(blank=True, null=True, upload_to='fasta_files/'),
        ),
    ]
