# Generated by Django 3.2.25 on 2024-08-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_alter_datafile_associated_fasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Job processing beginning'), ('PROCESSING_INPUTS', 'Identifying input files for staging'), ('STAGING_INPUTS', 'Transferring job input data to execution system'), ('STAGING_JOB', 'Staging runtime assets to execution system'), ('SUBMITTING_JOB', 'Submitting job to execution system'), ('QUEUED', 'Job queued to execution system queue'), ('RUNNING', 'Job running on execution system'), ('ARCHIVING', 'Transferring job output to archive system'), ('BLOCKED', 'Job blocked'), ('PAUSED', 'Job processing suspended'), ('FINISHED', 'Job completed successfully'), ('CANCELLED', 'Job execution intentionally stopped'), ('FAILED', 'Job failed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
