# Generated by Django 3.2.25 on 2024-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
