# Generated by Django 3.2.25 on 2024-08-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_job_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blast_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='TrimJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
            ],
        ),
        migrations.CreateModel(
            name='ConsensusJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_file_consensus_job', to='backend.datafile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
                ('reverse_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_file_consensus_job', to='backend.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='ConsensusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_align', models.TextField()),
                ('reverse_align', models.TextField()),
                ('consensus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='BlastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=16)),
                ('details', models.TextField()),
                ('length', models.CharField(max_length=5)),
                ('evalue', models.CharField(max_length=32)),
                ('mismatches', models.CharField(max_length=5)),
                ('sequence', models.TextField()),
                ('bitscore', models.CharField(max_length=8)),
                ('blast_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blastdata')),
            ],
        ),
        migrations.CreateModel(
            name='BlastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clade', models.CharField(default='default', max_length=8)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
            ],
        ),
    ]
