# Generated by Django 3.2.25 on 2024-08-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_blastdata_blastjob_blastresult_consensusdata_consensusjob_trimjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_input', models.FileField(blank=True, null=True, upload_to='muscle_files/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
                ('muscle_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.musclejob')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_alignment', models.FileField(blank=True, null=True, upload_to='alignment_files/')),
                ('muscle_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.musclejob')),
            ],
        ),
    ]
