# Generated by Django 3.2.25 on 2024-08-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_muscledata_musclefile_musclejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=109, on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
            preserve_default=False,
        ),
    ]
