# Generated by Django 3.2.25 on 2024-08-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_job_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylipNJJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgroup', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='PhylipNJData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outtree', models.TextField()),
                ('phylipnj_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.phylipnjjob')),
            ],
        ),
        migrations.CreateModel(
            name='PhylipMLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgroup', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='PhylipMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outtree', models.TextField()),
                ('phylipml_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.phylipmljob')),
            ],
        ),
    ]
