# Generated by Django 3.2.25 on 2024-08-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_phylipmldata_phylipmljob_phylipnjdata_phylipnjjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('variations', models.CharField(max_length=8)),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence1', models.CharField(max_length=255)),
                ('sequence2', models.CharField(max_length=255)),
                ('similarity_percentage', models.FloatField()),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bases', models.TextField()),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleConservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('value', models.FloatField()),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservations', to='backend.muscledata')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleConsensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('muscle_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consensus', to='backend.muscledata')),
            ],
        ),
    ]
