# Generated by Django 3.2.25 on 2024-09-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_muscleconsensus_muscleconservation_musclesequence_musclesimilarity_musclevariation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NanoporeSampleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NanoporeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='nanopore_sequences/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNanoporeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nanoporesequence')),
            ],
        ),
    ]
