# Generated by Django 3.2.25 on 2024-09-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_nanoporesampleset_nanoporesequence_projectnanoporesequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnanoporesequence',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
        ),
    ]
