# Generated by Django 3.2.25 on 2024-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_projectnanoporesequence_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnanoporesequence',
            old_name='project_id',
            new_name='project',
        ),
    ]
