# Generated by Django 3.2.25 on 2024-09-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_project_id_projectnanoporesequence_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_file', models.FileField(upload_to='fastp_output/')),
                ('json_file', models.FileField(upload_to='fastp_output/')),
                ('html_file', models.FileField(upload_to='fastp_output/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('project_nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectnanoporesequence')),
            ],
        ),
        migrations.CreateModel(
            name='FastpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nanoporesequence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'unique_together': {('nanopore_sequence', 'project')},
            },
        ),
    ]
