# Generated by Django 3.2.25 on 2024-09-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_fastpjob_fastpresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorechopResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chopped_file', models.FileField(upload_to='porechop_output/')),
                ('html_log_file', models.FileField(upload_to='porechop_output/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('project_nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectnanoporesequence')),
            ],
        ),
        migrations.CreateModel(
            name='PorechopJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nanoporesequence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
