# Generated by Django 3.2.25 on 2024-09-09 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_porechopjob_porechopresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedakaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_file', models.FileField(upload_to='medaka_files/')),
                ('fasta_file_medaka_headers', models.FileField(upload_to='medaka_files/')),
                ('medaka_output_dir', models.FilePathField(match='.*', path='medaka_output/', recursive=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectnanoporesequence')),
            ],
        ),
        migrations.CreateModel(
            name='MedakaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nanopore_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.nanoporesequence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
