# Generated by Django 3.2.25 on 2024-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_medakajob_medakaresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanoporesampleset',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
    ]
