# Generated by Django 3.2.25 on 2024-09-20 14:05

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_nanoporesampleset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=backend.models.reference_file_path)),
            ],
        ),
        migrations.AlterField(
            model_name='datafile',
            name='read_type',
            field=models.CharField(choices=[('F', 'Forward'), ('R', 'Reverse'), ('C', 'Consensus'), ('E', 'Reference')], max_length=1),
        ),
        migrations.AddField(
            model_name='datafile',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.referencedata'),
        ),
    ]
