# Generated by Django 3.2.25 on 2024-09-24 15:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20240920_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('abi', 'ABI File'), ('fasta', 'FASTA File')], max_length=8)),
                ('file', models.FileField(upload_to=backend.models.sample_file_path)),
            ],
        ),
        migrations.AlterField(
            model_name='datafile',
            name='read_type',
            field=models.CharField(choices=[('F', 'Forward'), ('R', 'Reverse'), ('C', 'Consensus'), ('E', 'Reference'), ('B', 'BLAST Hit')], max_length=1),
        ),
    ]
