# Generated by Django 3.2.25 on 2024-09-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20240924_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='sample_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.sampledata'),
        ),
    ]
