# Generated by Django 3.2.25 on 2024-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_datafile_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='left_trim',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='datafile',
            name='right_trim',
            field=models.TextField(default=''),
        ),
    ]
