# Generated by Django 3.2.25 on 2024-10-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20241007_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlastDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clade', models.CharField(default='default', max_length=8)),
                ('project_data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectdatafile')),
            ],
        ),
    ]
