# Generated by Django 3.2.25 on 2024-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_projectblastdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicity',
            name='middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Non-Binary/Other'), ('-', 'I prefer not to share')], max_length=1),
        ),
    ]
