# Generated by Django 3.2.25 on 2024-10-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20241029_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fastpjob',
            unique_together=set(),
        ),
    ]
