# Generated by Django 3.2.25 on 2024-12-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_fastpjob_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='process_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='source',
            field=models.CharField(choices=[('sample', 'Sample'), ('reference', 'Reference'), ('bold', 'BOLD'), ('genbank', 'GenBank'), ('hit', 'Hit'), ('upload', 'Upload'), ('import', 'Import'), ('paste', 'Paste'), ('saved', 'Saved')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='datafile',
            name='source_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.datafile'),
        ),
    ]
