# Generated by Django 3.2.25 on 2024-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20241204_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
