# Generated by Django 3.2.25 on 2024-12-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_datafile_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='order_number',
            new_name='order_id',
        ),
    ]
