# Generated by Django 3.2.25 on 2024-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_rename_order_number_datafile_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='source',
            field=models.CharField(choices=[('sample', 'Sample'), ('reference', 'Reference'), ('bold', 'BOLD'), ('genbank', 'GenBank'), ('hit', 'Hit'), ('upload', 'Upload'), ('import', 'Import'), ('paste', 'Paste'), ('saved', 'Saved'), ('nanopore', 'Nanopore')], default='upload', max_length=20),
        ),
    ]
