# Generated by Django 3.2.25 on 2025-01-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_datafile_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codon', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_storing', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('genus', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('habitat', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_site', models.TextField(blank=True, null=True)),
                ('isolation_source', models.TextField(blank=True, null=True)),
                ('sample_collected_from_host', models.BooleanField(default=False)),
                ('host_organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('reproduction', models.CharField(blank=True, max_length=50, null=True)),
                ('life_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_used', models.CharField(blank=True, max_length=255, null=True)),
                ('datafile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='backend.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='backend.datafile')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.specimen')),
            ],
        ),
    ]
