# Generated by Django 3.2.25 on 2025-01-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_author_specimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscledata',
            name='original_associated_alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MuscleTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_trim', models.IntegerField(default=0)),
                ('right_trim', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muscle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim', to='backend.muscledata')),
            ],
        ),
    ]
