# Generated by Django 3.2.25 on 2025-01-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20250107_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscletrim',
            name='created_at',
        ),
    ]
