# Generated by Django 3.2.25 on 2025-01-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_muscletrim_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscletrim',
            name='muscle_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trim', to='backend.muscledata'),
        ),
    ]
