# Generated by Django 3.2.25 on 2025-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_muscletrim_muscle_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscledata',
            name='original_associated_alignment',
            field=models.FileField(blank=True, null=True, upload_to='alignment_files/'),
        ),
    ]
