# Generated by Django 3.2.25 on 2025-01-09 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_muscledata_original_associated_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
