# Generated by Django 3.2.25 on 2025-05-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20250110_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_phy_tutorial', models.BooleanField(default=False)),
                ('disable_ngs_tutorial', models.BooleanField(default=False)),
                ('disable_ub_tutorial', models.BooleanField(default=False)),
                ('disable_nanopore_phy_tutorial', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile')),
            ],
        ),
    ]
