# Generated by Django 3.2.25 on 2025-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_tutorialsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='barcode_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('mtDNA', 'mtDNA'), ('Viral', 'Viral'), ('rbcL', 'rbcL'), ('COI', 'COI'), ('16S', '16S'), ('ITS', 'ITS'), ('Other', 'Other')], default='Other', max_length=8),
        ),
    ]
