# Generated by Django 3.2.25 on 2025-06-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_project_barcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='nanopore_seq_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.nanoporesequence'),
        ),
    ]
